version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Building website..."
  post_build:
    commands:
      - echo "Deploying website to S3..."
      - aws s3 sync . s3://www.manojconnects.space --delete
      - echo "Website successfully deployed!"

artifacts:
  files:
    - '**/*'
  base-directory: .
