version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Checking AWS CLI installation..."
      - if ! command -v aws &> /dev/null; then pip install awscli; else echo "AWS CLI already installed"; fi

  pre_build:
    commands:
      - echo "Ensuring lambda folder exists..."
      - mkdir -p lambda  # Ensure the lambda folder exists

  build:
    commands:
      - echo "Zipping Lambda function folders..."
      - cd lambda
      - for dir in *; do 
          if [ -d "$dir" ]; then 
            zip -r "$dir.zip" "$dir"; 
          fi 
        done
      - cd ..

  post_build:
    commands:
      - echo "Deploying website to S3..."
      - aws s3 sync . s3://www.manojconnects.space --exclude "lambda/*" --exclude ".git/*" --exclude "node_modules/*" --delete
      
      - echo "Deploying Lambda function ZIPs to S3..."
      - for zipfile in lambda/*.zip; do 
          aws s3 cp "$zipfile" "s3://www.manojconnects.space/$zipfile"; 
        done
      
      - echo "Updating Lambda functions..."
      - for function in AWSREKOGNITION uploadBlog getMyPosts getBlogs INSERTLOGIN GETDETAILS; do 
          aws lambda update-function-code --function-name "$function" --s3-bucket www.manojconnects.space --s3-key "lambda/$function.zip" || echo "Failed to update $function"; 
        done
      
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: .
